apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-steiwjps
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-steiwjps 
  name: go-steiwjps
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-steiwjps
    weight: 100 
